# All the databases used by the system
databases:
  dev: "data/db.sqlite"
  stage: ""
  prod: ""

# For every table in the database, add an item here
models:
  mainDB:
    - Sensor
    - Reading
    
# this makes the navigation bar
keys:
  - 12345678
  - 87654321
  
okay_range:
  temp:
    high: 40
    low: 20
  humi:
    high: 100
    low: 0
  volt:
    high: 3.3
    low:  0.0
